version: 2
project_name: ticker-vim

before:
  hooks:
    - go mod download

builds:
  - id: macos
    main: ./main.go
    binary: ticker-vim
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w -X 'github.com/alexso/ticker-vim/v5/cmd.Version={{.Version}}'

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: alexso
    name: ticker-vim
